"
" dotvim : https://github.com/dotphiles/dotvim
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype off
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  "let g:vundles=['general', 'git', 'hg', 'programming', 'completion', 'ruby', 'python', 'misc']
  let g:vundles=['general', 'python', 'programming', 'html', 'completion', 'git', 'misc']
  let g:neocomplcache_enable_at_startup = 1
  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  " Bundle 'reponame'
  Bundle 'airblade/vim-gitgutter'
  Bundle 'terryma/vim-multiple-cursors'
  Bundle 'gregsexton/gitv'
  Bundle 'osyo-manga/vim-over'
  Bundle 'edkolev/tmuxline.vim'
  Bundle 'Shougo/unite.vim'
  Bundle 'rking/ag.vim'
  Bundle 'Yggdroot/indentLine'
  " Airline themes
  Bundle 'rcabralc/monokai-airline.vim'
  Bundle 'vim-airline/vim-airline-themes'
endif

" Override colorscheme from base16
let g:dotvim_colorscheme = 'base16-default-dark'

" Customize to your needs...

"NeoVim handles ESC keys as alt+key set this to solve the problem
if has('nvim')
   set timeout
   set timeoutlen=50
   set ttimeout
   set ttimeoutlen=50
endif

" map keys
" change buffer
if has('nvim')
   map <M-Right> :tabnext<CR>
   map <M-Left> :tabprev<CR>
else
   map <S-K> :bnext<CR>
   map <S-J> :bprev<CR>
endif

" vim-over command line
map <C-s> :OverCommandLine<CR>

" Tmuxline
let g:tmuxline_preset = {
      \'a'    : '#S',
      \'cwin' : ['#I #W'],
      \'win'  : ['#I #W'],
      \'x'    : ['%b', '%d'],
      \'y'    : '%A',
      \'z'    : ['#(sh $HOME/.local/bin/fuzzytime)'],
      \'options' : {'status-justify' : 'left'}}
