schedules:
  - tasks: '*'
    interval:
      minutes: 30

templates:
  tv:
    exists_series: /media/WD1TB/Series/   
    seen_info_hash: local
    deluge:
      path: /media/WD1TB/Series/  
      label: tv
    content_filter: 
      reject: 
        - '*.rar'
        - '*.wmv'
    regexp:
      reject:
        - ITA-ENG
        - WEBRIP
        - ReEnc
        - web-dl
        - SPASTiKUS
        - mSD
        - VisionX
        - AppleTV
        - GhostTV
        - MaRS
        - 330MB
        - 'SNEAK PEEK'

    series:
      settings:
        shows:
          quality: 720p
      shows:
        - 'American Horror Story'
        - Arrow
        - 'Brooklyn Nine-Nine'
        - Community
        - 'Doctor Who 2005'
        - 'Family Guy'
        - Fargo
        - 'Fear The Walking Dead'
        - 'Game of Thrones'
        - Gotham
        - 'Heroes Reborn'
        - 'Marvels Agents of S H I E L D'
        - 'Marvels Agent Carter'
        - 'New Girl'
        - Supergirl
        - 'The Amazing Race'
        - 'The Big Bang Theory'
        - 'The Walking Dead'

tasks:
  Showrss:
    rss: 
      url: http://showrss.info/rss.php?user_id=40985&hd=1&proper=0
      link:
        - link
        - magneturi
    template: tv
    priority: 10
    accept_all: yes

  Kat:
    rss: http://kat.ph/tv/?rss=1
    template: tv
    priority: 50

  ezRSS:
    rss: https://eztv.ag/ezrss.xml
    template: tv
    priority: 50

  RARBG:
    rss: https://rarbg.to/rssdd.php
    template: tv

  _TPB:
    rss:
      url: http://rss.thepiratebay.se/208
      link:
        - link
        - magneturi
    template: tv
    priority: 99
    verify_ssl_certificates: no
