secrets: secrets.yml
schedules:
  - tasks: '*'
    interval:
      minutes: 30

templates:
  tv:
    exists_series: /media/WD1TB/Series/
    seen_info_hash: local
    exec: notify-send -i deluge "Download {{title}}"
    deluge:
      path: /media/WD1TB/Series/
      label: tv
      ratio: 0.001
      removeatratio: yes
    content_filter:
      reject:
        - '*.rar'
        - '*.wmv'
    regexp:
      reject:
        - ITA-ENG
        - WEBRIP
        - ReEnc
        - web-dl
        - SPASTiKUS
        - mSD
        - VisionX
        - AppleTV
        - GhostTV
        - MaRS
        - 330MB
        - 'SNEAK PEEK'

    series:
      settings:
        shows:
          quality: 720p
          propers: 2 hours
      shows:
        - 'American Horror Story'
        - Arrow
        - 'Ash vs Evil Dead'
        - 'Brooklyn Nine-Nine'
        - Community
        - 'Doctor Who 2005'
        - 'Family Guy'
        - Fargo
        - 'Fear The Walking Dead'
        - 'Game of Thrones'
        - Gotham
        - 'Heroes Reborn'
        - 'Marvels Agents of S H I E L D'
        - 'Marvels Agent Carter'
        - 'New Girl'
        - Supergirl
        - 'The Amazing Race'
        - 'The Big Bang Theory'
        - 'The Walking Dead'

tasks:
  Showrss:
    rss:
      url: '{{ secrets.feeds.showrss }}'
      link:
        - link
        - magneturi
    template: tv
    priority: 10
    accept_all: yes

  PubFeeds:
    priority: 20
    template: tv
    inputs:
      #_Kat
      - rss: '{{ secrets.feeds.kat }}'
      # Kat_ettv
      - rss: '{{ secrets.feeds.kat_ettv }}'
      # Kat_rartv
      - rss: '{{ secrets.feeds.kat_rartv }}'
      # ezRSS
      - rss: '{{ secrets.feeds.ezrss }}'
      # RARBG
      - rss: '{{ secrets.feeds.rarbg }}'
      #_TPB
      #- rss: '{{ secrets.feeds.tpb }}'
