emulate sh -c 'source /etc/profile'
env EDITOR=vim
env TERM=xterm-256color

#------------------------------
# SSH Agent
#------------------------------
#SSH_AUTH_SOCK=$(ss -xl | grep -o '/run/user/1000/keyring-.*/ssh')
#[ -z "$SSH_AUTH_SOCK" ] || export SSH_AUTH_SOCK 
