typeset -U path
#if [ -d $HOME/.gem/ruby/*/bin ]; then
# path=($HOME/.gem/ruby/*/bin $path)
#fi

if [ -d $HOME/bin ]; then
 path=($HOME/bin $path)
fi

if [ -d $HOME/.bin ]; then
 path=($HOME/.bin $path)
fi

if [ -f /usr/bin/nvim ]; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
