typeset -U path
[ -d ~/.gem/ruby/*/bin ] && path=(~/.gem/ruby/*/bin $path)
[ -d ~/bin ] && path=(~/bin $path)
[ -d ~/.bin ] && path=(~/.bin $path)

if [ -f /usr/bin/nvim ]; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
