typeset -U path
if [ -d ~/.gem/ruby/*/bin ]; then
 path=(~/.gem/ruby/*/bin $path)
fi

if [ -d ~/bin ]; then
 path=(~/bin $path)
fi

fi [ -d ~/.bin ]; then
 path=(~/.bin $path)
fi

if [ -f /usr/bin/nvim ]; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
